---
  - set_fact:
      hub_product: "{{extract_location}}/gateway/wso2telcohub-{{hub_version}}"
      https_port: "9443"
      http_port: "9763"
      LB_port: "443"

#-------------------Copy registry.xml------------------
  - name: mig configurations in am gateway - copying registry.xml
    copy:
     src: "registry.xml"
     dest: "{{hub_product}}/repository/conf"

#-------------------Mysql Changes in registry.xml------------------
  - name: mig configurations in am gateway - Change dbConfig sharedregistry to govregistry repository/conf/registry.xml
    replace:
      dest: "{{hub_product}}/repository/conf/registry.xml"
      regexp: 'mysql_user'
      replace: '{{mysql_user}}'
      backup: no

  - name: mig configurations in am gateway - Change dbConfig sharedregistry to govregistry repository/conf/registry.xml
    replace:
      dest: "{{hub_product}}/repository/conf/registry.xml"
      regexp: 'mysql_port'
      replace: '{{mysql_port}}'
      backup: no

  - name: mig configurations in am gateway - Change dbConfig sharedregistry to govregistry repository/conf/registry.xml
    replace:
      dest: "{{hub_product}}/repository/conf/registry.xml"
      regexp: 'mysql_host'
      replace: '{{mysql_host}}'
      backup: no

#-------------------Change dbConfig sharedregistry to govregistry ------------------
  - name: mig configurations in am gateway - Change dbConfig sharedregistry to govregistry repository/conf/registry.xml
    replace:
      dest: "{{hub_product}}/repository/conf/registry.xml"
      regexp: 'sharedregistry'
      replace: 'govregistry'
      backup: no

#-------------------Change offset---------------------------
#-------------------Copy api-manager.xml to hub-------------------
  - name: mig configurations in am gateway - copying api-manager.xml to repository/conf
    copy:
     src: "api-manager.xml"
     dest: "{{hub_product}}/repository/conf/api-manager.xml"

#-------------------Point AuthManager and APIKeyValidator to IS------------------

#------ replacing the port and the IP  with the DNS name ----------------

#  - name: mig configurations in am gateway - Point AuthManager and APIKeyValidator to IS
#    replace:
#      dest: "{{hub_product}}/repository/conf/api-manager.xml"
#      regexp: 'IS_NAME'
#      replace: '{{mig_host}}:{{(https_port|int) + (mig_offset|int)}}'
#      backup: no

  - name: mig configurations in am gateway - Point AuthManager and APIKeyValidator to IS
    replace:
      dest: "{{hub_product}}/repository/conf/api-manager.xml"
      regexp: 'IS_NAME'
      replace: '{{mig_host}}:{{(LB_port|int)}}'
      backup: no

#-------------------Change KeyValidatorClientType in api-manager.xml in hub------------------
  - name: mig configurations in am gateway - Change KeyValidatorClientType in api-manager.xml in hub
    replace:
      dest: "{{hub_product}}/repository/conf/api-manager.xml"
      regexp: '<KeyValidatorClientType>ThriftClient</KeyValidatorClientType>'
      replace: '<KeyValidatorClientType>WSClient</KeyValidatorClientType>'
      backup: no

#-------------------Change EnableThriftServer to false in api-manager.xml in hub------------------
  - name: mig configurations in am gateway - Change EnableThriftServer in api-manager.xml in hub
    replace:
      dest: "{{hub_product}}/repository/conf/api-manager.xml"
      regexp: '<EnableThriftServer>true</EnableThriftServer>'
      replace: '<EnableThriftServer>false</EnableThriftServer>'
      backup: no

  - name: mig configurations in am gateway - Change 'localhost' to domain name in api-manager.xml in portal
    replace:
      dest: "{{hub_product}}/repository/conf/api-manager.xml"
      regexp: 'LOCALHOST'
      replace: '{{gateway_host}}'
      backup: no

#-------------------Point AuthorizedAPI, RevokeAPI and TokenAPI to IS------------------
#  - name: mig configurations in am gateway - Point AuthorizedAPI to IS
#    replace:
#      dest: "{{hub_product}}/repository/deployment/server/synapse-configs/default/api/_AuthorizeAPI_.xml"
#      regexp: 'https://{uri.var.hostname}:{uri.var.portnum}'
#      replace: 'https://{{mig_host}}:{{(https_port|int) + (mig_offset|int)}}'
#      backup: no
#
#  - name: mig configurations in am gateway - Point RevokeAPI to IS
#    replace:
#      dest: "{{hub_product}}/repository/deployment/server/synapse-configs/default/api/_RevokeAPI_.xml"
#      regexp: 'https://{uri.var.hostname}:{uri.var.portnum}'
#      replace: 'https://{{mig_host}}:{{(https_port|int) + (mig_offset|int)}}'
#      backup: no
#
#  - name: mig configurations in am gateway - Point TokenAPI to IS
#    replace:
#      dest: "{{hub_product}}/repository/deployment/server/synapse-configs/default/api/_TokenAPI_.xml"
#      regexp: 'https://{uri.var.hostname}:{uri.var.portnum}'
#      replace: 'https://{{mig_host}}:{{(https_port|int) + (mig_offset|int)}}'
#      backup: no
##--------------------- Comment the following on requirement ---------------
  - name: mig configurations in am gateway - Point AuthorizedAPI to IS
    replace:
      dest: "{{hub_product}}/repository/deployment/server/synapse-configs/default/api/_AuthorizeAPI_.xml"
      regexp: 'https://{uri.var.hostname}:{uri.var.portnum}'
      replace: 'https://{{mig_host}}:{{(LB_port|int)}}'
      backup: no

  - name: mig configurations in am gateway - Point RevokeAPI to IS
    replace:
      dest: "{{hub_product}}/repository/deployment/server/synapse-configs/default/api/_RevokeAPI_.xml"
      regexp: 'https://{uri.var.hostname}:{uri.var.portnum}'
      replace: 'https://{{mig_host}}:{{(LB_port|int)}}'
      backup: no

  - name: mig configurations in am gateway - Point TokenAPI to IS
    replace:
      dest: "{{hub_product}}/repository/deployment/server/synapse-configs/default/api/_TokenAPI_.xml"
      regexp: 'https://{uri.var.hostname}:{uri.var.portnum}'
      replace: 'https://{{mig_host}}:{{(LB_port|int)}}'
      backup: no

#-------------------Change Host name ------------------
  - name: configure DAS - Change Host name in repository/conf/carbon.xml
    replace:
      dest: "{{hub_product}}/repository/conf/carbon.xml"
      regexp: '<!--HostName>www.wso2.org</HostName-->'
      replace: '<HostName>{{gateway_host}}</HostName>'
      backup: no

  - name: configure DAS - Change MgtHostName name in repository/conf/carbon.xml
    replace:
      dest: "{{hub_product}}/repository/conf/carbon.xml"
      regexp: '<!--MgtHostName>mgt.wso2.org</MgtHostName-->'
      replace: '<MgtHostName>{{gateway_host}}</MgtHostName>'
      backup: no

#-------------------Start the identity server-------------------
  - name: mig configurations in am gateway - Start API Manager
    shell: "{{hub_product}}/bin/./wso2server.sh start"
    ignore_errors: True

#-------------------Wait for server to start-------------------
  - name: mig configurations in am gateway - Wait for server to start
    wait_for:
      port: "{{(https_port|int)+(gateway_offset|int)}}"
      delay: 5
    ignore_errors: True
