---

  - set_fact:
     esb_pack: "{{esb_extract_location}}/wso2esb-{{esb_version}}"

#-------------------Remove the existing certificate files-------------------
  - name: certificate configuration in the mediation - Remove the existing wso2carbon.jks file before copying the new certificate file
    file:
      path: "{{esb_pack}}/repository/resources/security/wso2carbon.jks"
      state: absent
    ignore_errors: False

#-------------------Copy the certificate files-------------------
  - name: certificate configuration in the mediation - copying certificate file - wso2carbon.jks
    copy:
     src: "wso2carbon.jks"
     dest: "{{esb_pack}}/repository/resources/security/"
    ignore_errors: False

#-------------------Remove the existing certificate files-------------------
  - name: certificate configuration in the mediation - Remove the existing client-truststore.jks file before copying the new certificate file
    file:
      path: "{{esb_pack}}/repository/resources/security/client-truststore.jks"
      state: absent
    ignore_errors: False

#-------------------Copy the certificate files-------------------
  - name: certificate configuration in the mediation - copying certificate file - client-truststore.jks
    copy:
     src: "client-truststore.jks"
     dest: "{{esb_pack}}/repository/resources/security/"
    ignore_errors: False

#----------------------Configuring keystores in carbon.xml----------------------------------------
  - name: certificate configuration in the mediation - Configuring keystores in carbon.xml - Password
    replace:
      dest: "{{esb_pack}}/repository/conf/carbon.xml"
      regexp: '<Password>wso2carbon</Password>'
      replace: '<Password>{{httpsPassword}}</Password>'
      backup: no

  - name: certificate configuration in the mediation - Configuring keystores in carbon.xml - KeyAlias
    replace:
      dest: "{{esb_pack}}/repository/conf/carbon.xml"
      regexp: '<KeyAlias>wso2carbon</KeyAlias>'
      replace: '<KeyAlias>{{KeyAlias}}</KeyAlias>'
      backup: no

  - name: certificate configuration in the mediation - Configuring keystores in carbon.xml
    replace:
      dest: "{{esb_pack}}/repository/conf/carbon.xml"
      regexp: '<KeyPassword>wso2carbon</KeyPassword>'
      replace: '<KeyPassword>{{httpsPassword}}</KeyPassword>'
      backup: no

#----------------------Configuring keystores in axis2.xml----------------------------------------
  - name: certificate configuration in the mediation - Configuring keystores in axis2.xml - Password
    replace:
      dest: "{{esb_pack}}/repository/conf/axis2/axis2.xml"
      regexp: '<Password>wso2carbon</Password>'
      replace: '<Password>{{httpsPassword}}</Password>'
      backup: no

  - name: certificate configuration in the mediation - Configuring keystores in axis2.xml - KeyPassword
    replace:
      dest: "{{esb_pack}}/repository/conf/axis2/axis2.xml"
      regexp: '<KeyPassword>wso2carbon</KeyPassword>'
      replace: '<KeyPassword>{{httpsPassword}}</KeyPassword>'
      backup: no

#--------------------------- configuring keystores for security in identity.xml--------------------------------
  - name: certificate configuration in the mediation - Configuring keystores for security in identity.xml
    replace:
      dest: "{{esb_pack}}/repository/conf/identity/identity.xml"
      regexp: '<Password>wso2carbon</Password>'
      replace: '<Password>{{httpsPassword}}</Password>'
      backup: no

#----------------------Configuring keystores in catalina-server.xml----------------------------------------
  - name: certificate configuration in the mediation - Configuring keystores in catalina-server.xml
    replace:
      dest: "{{esb_pack}}/repository/conf/tomcat/catalina-server.xml"
      regexp: 'keystorePass="wso2carbon"'
      replace: 'keystorePass="{{httpsPassword}}"'
      backup: no
