---
# vars file for aws_automation
## Update the following arrays with the intances you need to start

hub_zip_location: /mnt
mig_zip_location: /mnt
zip_location: /mnt
hub_version: 3.0.2
is_version: 2.2.0
AM_url: https://s3.amazonaws.com/sftp-release-binaries/sftp/dep/3_0_X/wso2telcohub-3.0.2.zip
MIG_url: http://maven.wso2telco.com/nexus/content/repositories/releases/com/wso2telco/product/ids/wso2telcoids/2.2.0/wso2telcoids-2.2.0.zip
