---
# CHANGE THE FOLLOWING PROPERTIES ACCORDINGLY


extract_location: /mnt      # give the same extract loacation as in the role, 'download_AM_for_server'
product_version: 3.0.2
portal_offset: 1

httpsPassword: wso2telco@123
KeyAlias: ncelwso2telco

patch_location: /mnt/patches
