---

- name: Internal gateway setup automation process
  hosts: MIG_server_1
  become: true
  become_method: sudo
  gather_facts: True
  tags: MIG

  roles:
    - configure_the_MIG1_clustering
    - km_configuration_in_MIG
    - configure_MIG_security

- name: Internal gateway setup automation process
  hosts: MIG_server_2
  become: true
  become_method: sudo
  gather_facts: True
  tags: MIG

  roles:
    - configure_the_MIG2_clustering
    - km_configuration_in_MIG
    - configure_MIG_security