---
#-------------------Start the identity server-------------------

  - name: download the wso2telco DAS manager to the DAS servers
    get_url:
      url: "{{download_link}}"
      dest: "{{zip_location}}/wso2analytics-hub-{{product_version}}.zip"
      mode: 0755
